### ISSUE TITLE
Cannot read property 'string' of undefined

### ISSUE THREAD

**Issue by punky97** [wayofthefuture/react-input-moment#4]
Hi guys,
Im using this InputMoment, i saw your demo so beautiful and I decided to use it.
But when i tried to inmport it to my project with ["import {InputMoment} from 'react-input-moment';"] there was a problem.
My browser said :
     Uncaught TypeError: Cannot read property 'string' of undefined
and I found this : 
module.exports = React.createClass({
  displayName: 'InputSlider',

  propTypes: {
    axis: **React.PropTypes.string,**
    ....
    
Can anyone help me ?
Thank you!

**Comment by smeijer** [comment]
The issue here is the React version.  React 16 doesn't have a `PropTypes` property any more. For that you should import the `prop-types` package.

The real problem lies in the `react-input-slider` dependency, as this project (`react-input-moment`) doesn't have any proptypes defined. I see the last version of https://github.com/wangzuo/react-input-slider already does use `prop-types` instead of `React.PropTypes`. So an update could help here.

**Comment by wayofthefuture** [comment]
I posted an issue in react-input-slider about that, they fixed it already it? If an update will fix it please let me know i'll take care of it hopefully soon.

**Comment by smeijer** [comment]
Untested; but I expect that updating `react-input-slider` to `v4` would fix this issue. As they are using `prop-types` already.

**Comment by wayofthefuture** [comment]
Ready for a PR, thanks!

**Comment by wayofthefuture** [comment]
Please create a pull request and I'll merge.

**Comment by wayofthefuture** [comment]
Please update and try again and let me know if it works, thanks.
